#!/bin/bash -eu

echo -n "Compiling AFLplusplus ..."

# Build and install AFLplusplus tools necessary for fuzzing.
pushd $SRC/AFLplusplus > /dev/null

# Unset CFLAGS and CXXFLAGS while building AFLplusplus since we don't want to slow it
# down with sanitizers.
INITIAL_CXXFLAGS=$CXXFLAGS
INITIAL_CFLAGS=$CFLAGS
unset CXXFLAGS
unset CFLAGS
make clean && make distrib && make install
CFLAGS=$INITIAL_CFLAGS
CXXFLAGS=$INITIAL_CXXFLAGS

popd > /dev/null

echo " done."

